export const tabledatatwo = [
  {
    s_no: "1",
    division: "Ujjain",
    district: "Agar",
    ulb_name: "Agar",
    ulb_type: "Nagar Parishad",
    sla_time: "15 Days",
    submitted: "970",
    sanctioned: "788",
    average: "368",
    median: "31",
    min_days_taken: "8",
    max_days_taken: "734",
  },
  {
    s_no: "2",
    division: "Bhopal",
    district: "Agar",
    ulb_name: "Agar",
    ulb_type: "Nagar Parishad",
    sla_time: "15 Days",
    submitted: "970",
    sanctioned: "788",
    average: "368",
    median: "31",
    min_days_taken: "8",
    max_days_taken: "734",
  },
  {
    s_no: "3",
    division: "Ujjain",
    district: "Agar",
    ulb_name: "Agar",
    ulb_type: "Nagar Parishad",
    sla_time: "15 Days",
    submitted: "970",
    sanctioned: "788",
    average: "368",
    median: "31",
    min_days_taken: "8",
    max_days_taken: "734",
  },
  {
    s_no: "4",
    division: "Ujjain",
    district: "Agar",
    ulb_name: "Agar",
    ulb_type: "Nagar Parishad",
    sla_time: "15 Days",
    submitted: "970",
    sanctioned: "788",
    average: "368",
    median: "31",
    min_days_taken: "8",
    max_days_taken: "734",
  },
  {
    s_no: "5",
    division: "Ujjain",
    district: "Agar",
    ulb_name: "Agar",
    ulb_type: "Nagar Parishad",
    sla_time: "15 Days",
    submitted: "970",
    sanctioned: "788",
    average: "368",
    median: "31",
    min_days_taken: "8",
    max_days_taken: "734",
  },
  {
    s_no: "6",
    division: "Ujjain",
    district: "Agar",
    ulb_name: "Agar",
    ulb_type: "Nagar Parishad",
    sla_time: "15 Days",
    submitted: "970",
    sanctioned: "788",
    average: "368",
    median: "31",
    min_days_taken: "8",
    max_days_taken: "734",
  },
  {
    s_no: "7",
    division: "Ujjain",
    district: "Agar",
    ulb_name: "Agar",
    ulb_type: "Nagar Parishad",
    sla_time: "15 Days",
    submitted: "970",
    sanctioned: "788",
    average: "368",
    median: "31",
    min_days_taken: "8",
    max_days_taken: "734",
  },
  {
    s_no: "8",
    division: "Ujjain",
    district: "Agar",
    ulb_name: "Agar",
    ulb_type: "Nagar Parishad",
    sla_time: "15 Days",
    submitted: "970",
    sanctioned: "788",
    average: "368",
    median: "31",
    min_days_taken: "8",
    max_days_taken: "734",
  },
  {
    s_no: "9",
    division: "Ujjain",
    district: "Agar",
    ulb_name: "Agar",
    ulb_type: "Nagar Parishad",
    sla_time: "15 Days",
    submitted: "970",
    sanctioned: "788",
    average: "368",
    median: "31",
    min_days_taken: "8",
    max_days_taken: "734",
  },
  {
    s_no: "10",
    division: "Ujjain",
    district: "Agar",
    ulb_name: "Agar",
    ulb_type: "Nagar Parishad",
    sla_time: "15 Days",
    submitted: "970",
    sanctioned: "788",
    average: "368",
    median: "31",
    min_days_taken: "8",
    max_days_taken: "734",
  },
];
